taller/login/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from login.views import *
from login.api import *

urlpatterns = [
        path('modulos/', modulos, name='menu_modulos'), 
        path('login_menu/', login_v, name='login_v'), 
        path('login/',auth_views.LoginView.as_view(template_name='base/login.html'), name='login'),
        path('logout/',auth_views.LogoutView.as_view(template_name='base/login.html'), name='logout'),

        path('usuario/listado/',UsuarioListar.as_view(), name='listado_usuario'),
        path('usuario/nueva/', UsuarioCrear.as_view(), name='nuevo_usuario'),
        path('usuario/editar/<int:pk>', UsuarioModificar.as_view(), name='modificar_usuario'),
        path('usuario/estado/<int:pk>/<str:estado>', EstadoUsuario, name='estado_usuario'),
        path('usuario/permisos/<int:pk>',PermisosUsuarios, name='permisos_usuario'),
        path('usuario/permisos/', UsuariosPermisos.as_view(), name="permisos_usuario_post"),

        #####grupos de usuarios
        path('grupo/listado/',GrupoListar.as_view(), name='GrupoListar'),
        path('grupo/nuevo/', GrupoUsuarioCrear.as_view(), name='GrupoUsuarioCrear'),
        path('grupo/editar/<int:pk>', GrupoUsuarioUpdate.as_view(), name='GrupoUsuarioUpdate'),
        path('grupo/eliminar/<int:pk>', GrupousuarioDelete.as_view(), name='GrupousuarioDelete'),
        path('grupo/permisos/<int:pk>',PermisosGrupos, name='PermisosGrupos'),
        path('grupo/permisos_api/', GruposPermisos.as_view(), name="permisos_grupo_post"),
        path('grupo/permisos_usuario/<int:pk>',PermisosGruposusuarios, name='PermisosGruposusuarios'),
        path('grupo/permisos_usuario_api/', GruposUsuariosPermisos.as_view(), name="GruposUsuariosPermisos"),
    
]       

taller/stock/urls.py
from django.urls import path, include
from stock.views import *
from stock.api import *

urlpatterns = [
    
        path('stock/', stock_v, name='stock'), 

        ###Ubicaciones
        path('ubicacion/listado/',UbicacionListView.as_view(), name='UbicacionListView'),
        path('ubicacion/nuevo/',UbicacionCreateView.as_view(), name='UbicacionCreateView'),
        path('ubicacion/editar/<int:pk>', UbicacionUpdateView.as_view(), name='UbicacionUpdateView'),
        path('ubicacion/eliminar/<int:pk>', UbicaciondeleteView.as_view(), name='UbicaciondeleteView'),


        #Recepcion producto
        path('recepcion/listado/',ProductosRecepcionList, name='ProductosRecepcionList'),
        path('recepcion/crear/<int:id>', ProductosRecepcionCreate, name='ProductosRecepcionCreate'),

        #Moviemiento stock
        path('movimiento/listado/',MSListado, name='MSListado'),
        path('movimiento/create/',MSCreateUpdate, name='MSCreateUpdate'),
        path('movimiento/ubicacion/<str:ubicacion>',datos_items, name='datos_items'),
        path('movimiento/item_catidad/<str:ubicacion>/<int:item>',verificar_cantidad, name='verificar_cantidad'),
        path('movimiento/detail/<int:pk>',MSDetalle.as_view(), name='MSDetalle'),
        path('movimiento/delete/<int:pk>',MSDelete, name='MSDelete'),

        ###Adaptacion de Stock
        path('adaptacion/listado/',AdaptacionStock, name='AdaptacionStock'),
        path('adaptacion/verificacion/<str:ubicacion>/<str:operacion>',ajuste_stock, name='ajuste_stock'),
        path('adaptacion/create/',ASCreateUpdate, name='ASCreateUpdate'),
        path('adaptacion/detail/<int:pk>',ASDetalle.as_view(), name='ASDetalle'),
        path('adaptacion/delete/<int:pk>',ASDelete, name='ASDelete'),

        ###periodo
        path('periodo/listado/',PeriodoInventarioListView.as_view(), name='PeriodoList'),
        path('periodo/create/',PeriodoInventarioCreateView.as_view(), name='PeriodoCreate'),
        path('periodo/update/<int:pk>',PeriodoInventarioUpdate.as_view(), name='PeriodoUpdate'),
        path('periodo/aviso/',aviso_inventario, name='aviso_inventario'),
        path('periodo/delete/<int:pk>',PeriodoInventariodelete.as_view(), name='PeriodoDelete'),
        path('periodo/activar/<int:pk>',Activar_periodo, name='Activar_periodo'),
        path('periodo/deactivar/<int:pk>',estado_inactivar, name='estado_inactivar'),


]       

taller/taller/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('App/login/', include('login.urls')),
    path('App/compras/', include('compras.urls')),
    path('App/stock/', include('stock.urls')),
    path('App/ventas/', include('ventas.urls')),
]

taller/stock/models.py
from django.db import models
from compras.models import *
# Create your models here.
from django.utils import timezone

class Ubicaciones(models.Model):
    nombre = models.CharField(max_length=500, null=True, blank=True, verbose_name="Ubicación")
    departamento = models.ForeignKey(Departamentos, verbose_name="Departamentos",  on_delete=models.PROTECT, null=True,
                                   blank=True)
    estado = models.CharField(max_length=1, default="A")
    creado_por = models.ForeignKey(User, on_delete=models.PROTECT, null=True,
                                   blank=True, related_name='cc')
    modificado_por = models.ForeignKey(User, on_delete=models.PROTECT, null=True,
                                       blank=True, related_name='rrrr')
    creado_el = models.DateTimeField(null=True, blank=True)
    modificado_el = models.DateTimeField(null=True, blank=True)
    # class Meta:
    #     managed = False
    #     db_table = 'core_depositos'

    def __str__(self):
        return str(self.nombre) 

class Recepcionproducto(models.Model):
    orden = models.ForeignKey(OrdenCompra, on_delete=models.PROTECT)
    numero = models.IntegerField()
    fecha = models.DateField()
    
    class Meta:
        managed = False
        db_table = 'v_recepcion'  

class Lote(models.Model):
    costo_item = models.DecimalField(max_digits=17, decimal_places=2, null=True, blank=True)
    fecha_lote = models.DateField(null=True, blank=True)
    fecha_vencimiento = models.DateField(null=True, blank=True)
    estado = models.CharField(max_length=20, null=True, blank=True)
    item = models.ForeignKey(Item, on_delete=models.PROTECT,null=True, blank=True)


class Stock(models.Model):
    ubicacion = models.ForeignKey(Ubicaciones, on_delete=models.PROTECT,null=True, blank=True)
    lote = models.ForeignKey(Lote, on_delete=models.PROTECT,null=True, blank=True)
    item = models.ForeignKey(Item, on_delete=models.PROTECT,null=True, blank=True, related_name="articulo")
    cantidad = models.DecimalField(max_digits=20, decimal_places=3)
    stock = models.IntegerField(null=True)
    operacion = models.CharField(max_length=50, null=True, blank=True)
    referencia = models.IntegerField(null=True)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT,null=True, blank=True)
    fecha_insercion = models.DateTimeField(null=True, blank=True)

def trxStock(origen, item, cantidad, operacion, referencia, usuario, destino=None):
    print ("cantidad", type(cantidad))
    # ajuste baja, entrega de utiles, movimiento baja
    #if operacion == "NUEVO AJUSTE BAJA" or operacion == "NUEVA ENTREGA UTILES" or operacion == "NUEVO MOVIMIENTO BAJA":
    if operacion == "NUEVO MOVIMIENTO BAJA" or operacion == "SOLICITUD APROBADA BAJA":
        print ("Entro 1")
        cantidad = int(cantidad)
        while cantidad > 0:
            s = Stock.objects.filter(item=item, ubicacion=origen, stock__gt=0, lote__estado='A').order_by('lote_id','-fecha_insercion')
            print (s)
            if s:
                stock = s[0].stock
            else:
                stock = 0

            parcial = 0

            if cantidad > stock:
                parcial = stock
            else:
                parcial = cantidad

            xs = Stock.objects.filter(item=item, ubicacion=origen, lote__estado='A').order_by('-fecha_insercion')
            if xs:
                xstock = xs[0].stock
            else:
                xstock = 0
            print ("parcial: ", type(parcial))

            nstock = xstock - parcial

            Stock.objects.create(ubicacion=s[0].ubicacion, item=s[0].item, lote=s[0].lote, cantidad=parcial, stock=nstock, usuario=usuario,
                                 fecha_insercion=timezone.now(), referencia=referencia, operacion=operacion)

            cantidad -= parcial
            lote = Lote()
            lote.item = item
            lote.fecha_lote = timezone.now().date()
            lote.fecha_vencimiento = s[0].lote.fecha_vencimiento
            lote.costo_item = s[0].lote.costo_item
            lote.estado = 'A'
            lote.save()
            xs = Stock.objects.filter(item=item, ubicacion=destino, lote__estado='A').order_by('-fecha_insercion')
            if xs:
                xstock = xs[0].stock
            else:
                xstock = 0
            xstock += parcial
            if operacion == "NUEVO MOVIMIENTO BAJA":
                Stock.objects.create(ubicacion=destino, item=item, lote=lote, cantidad=parcial, stock=xstock,
                                     usuario=usuario,
                                     fecha_insercion=timezone.now(), referencia=referencia, operacion='NUEVO MOVIMIENTO ALTA')
            elif operacion == "SOLICITUD APROBADA BAJA":
                print( "Entro 2")
                Stock.objects.create(ubicacion=destino, item=item, lote=lote, cantidad=parcial, stock=xstock,
                                     usuario=usuario,
                                     fecha_insercion=timezone.now(), referencia=referencia,
                                     operacion='SOLICITUD APROBADA ALTA')
    elif operacion == "NUEVO AJUSTE BAJA":
        while cantidad > 0:
            s = Stock.objects.filter(item=item, ubicacion=origen, stock__gt=0, lote__estado='A').order_by('lote_id',
                                                                                                         '-fecha_insercion')
            if s:
                stock = s[0].stock
            else:
                stock = 0

            parcial = 0

            if cantidad > stock:
                parcial = stock
            else:
                parcial = cantidad

            xs = Stock.objects.filter(item=item, ubicacion=origen, lote__estado='A').order_by('-fecha_insercion')
            if xs:
                xstock = xs[0].stock
            else:
                xstock = 0

            nstock = xstock - parcial

            Stock.objects.create(ubicacion=s[0].ubicacion, item=s[0].item, lote=s[0].lote, cantidad=parcial, stock=nstock,
                                 usuario=usuario,
                                 fecha_insercion=timezone.now(), referencia=referencia, operacion=operacion)
            cantidad -= parcial
    elif operacion == "NUEVO AJUSTE ALTA":
        s = Stock.objects.filter(item=item, ubicacion=origen, lote__estado='A').order_by('-lote_id', '-fecha_insercion')
        lote = Lote()
        lote.item = item
        lote.fecha_lote = timezone.now().date()
        lote.fecha_vencimiento = None
        lote.costo_item = s[0].lote.costo_item
        lote.estado = 'A'
        lote.save()
        xs = Stock.objects.filter(item=item, ubicacion=origen, lote__estado='A').order_by('-fecha_insercion')
        if xs:
            xstock = xs[0].stock
        else:
            xstock = 0
        xstock += cantidad
        Stock.objects.create(ubicacion=origen, item=item, lote=lote, cantidad=cantidad, stock=xstock,
                             usuario=usuario,
                             fecha_insercion=timezone.now(), referencia=referencia, operacion=operacion)
    elif operacion == "ANULAR MOVIMIENTO":
        movimientos = Stock.objects.filter(item=item,
                                           operacion__in=['NUEVO MOVIMIENTO BAJA', 'NUEVO MOVIMIENTO ALTA'],
                                           referencia=referencia)
        for mo in movimientos:
            xs = Stock.objects.filter(item=mo.item, ubicacion=mo.ubicacion, lote__estado='A').order_by('-fecha_insercion')
            if xs:
                xstock = xs[0].stock
            else:
                xstock = 0

            if mo.operacion == 'NUEVO MOVIMIENTO BAJA':
                Stock.objects.create(ubicacion=mo.ubicacion, item=mo.item, lote=mo.lote, cantidad=mo.cantidad, stock=xstock+mo.cantidad,
                                     usuario=usuario,
                                     fecha_insercion=timezone.now(), referencia=referencia,
                                     operacion='ANULAR MOVIMIENTO')
            elif mo.operacion == 'NUEVO MOVIMIENTO ALTA':
                Stock.objects.create(ubicacion=mo.ubicacion, item=mo.item, lote=mo.lote, cantidad=mo.cantidad, stock=xstock-mo.cantidad,
                                     usuario=usuario,
                                     fecha_insercion=timezone.now(), referencia=referencia,
                                     operacion='ANULAR MOVIMIENTO')
    elif operacion == "ANULAR SOLICITUD":
        movimientos = Stock.objects.filter(item=item,
                                           operacion__in=['SOLICITUD APROBADA BAJA', 'SOLICITUD APROBADA ALTA'],
                                           referencia=referencia)
        for mo in movimientos:
            xs = Stock.objects.filter(item=mo.item, ubicacion=mo.ubicacion, lote__estado='A').order_by('-fecha_insercion')
            if xs:
                xstock = xs[0].stock
            else:
                xstock = 0

            if mo.operacion == 'SOLICITUD APROBADA BAJA':
                Stock.objects.create(ubicacion=mo.ubicacion, item=mo.item, lote=mo.lote, cantidad=mo.cantidad, stock=xstock+mo.cantidad,
                                     usuario=usuario,
                                     fecha_insercion=timezone.now(), referencia=referencia,
                                     operacion='ANULAR SOLICITUD')
            elif mo.operacion == 'SOLICITUD APROBADA ALTA':
                Stock.objects.create(ubicacion=mo.ubicacion, item=mo.item, lote=mo.lote, cantidad=mo.cantidad, stock=xstock-mo.cantidad,
                                     usuario=usuario,
                                     fecha_insercion=timezone.now(), referencia=referencia,
                                     operacion='ANULAR SOLICITUD')
    elif operacion == "ANULAR AJUSTE ALTA":
        movimientos = Stock.objects.filter(item=item,
                                           operacion__in=['NUEVO AJUSTE ALTA'],

taller/stock/templates/AS/AS_create.html
{% extends 'base/index.html' %}
{% load static %}

{% block extrahead %}
    <script src="{% static 'datos/jquery.formset.js' %}" type="text/JavaScript"></script>
    <script src="{% static 'js/Inputmask/dist/jquery.inputmask.bundle.js' %}"></script>

    <script src="{% static 'adaptacion_stock/create.js' %}"></script>


{% endblock %}
{% block page_content %}
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">


    <div class="main-content-inner">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">

                        <h4 class="header-title">Nuevo/Modificar Adaptación de Stock</h4>
                        <form method="POST" enctype="multipart/form-data" class="form" id="formulario">
                            {% csrf_token %}
                            <div class="row">

                                <div class="col-sm-8">
                                    <table class="table"> 
                                        <tr>
                                            <th>Ubicación</th>
                                            <td>
                                                <select class="form-control" name="ubicacion" id="id_ubicacion" >
                                                    <option value="">----------</option>
                                                    {% for ubicacion in ubicaciones %}
                                                        <option value="{{ ubicacion.id }}">{{ ubicacion.nombre }}</option>
                                                    {% endfor %}
                                                </select>
                                            </td>
                                            
                                        </tr>
                                        <tr>
                                            <th>Procedimiento</th>
                                            <td>
                                                {{ form.operacion}}{{ form.operacion.errors }}
                                            </td>
                                        </tr>
                                        <tr>
                                            <th>Comentario</th>
                                            <td>
                                                {{ form.observacion}}{{ form.observacion.errors }}
                                            </td>
                                        </tr>
                                    </table>
                                    
                                <br>
                                
                            </div>
                           
                            <div class="col-md-12">
                                <hr>
                                <br>
                                <ul id="myTabedu1" class="tab-review-design">
                                    <li class="active"><a href="#description">Detalles</a></li>
                                </ul>
                                <div id="myTabContent" class="tab-content custom-product-edit">
                                    <div class="product-tab-list tab-pane fade active in" id="description">
                                        
                                        <table id="detalle_tabla" class="table table-striped jambo_table scroll">
                                            {{ formset.management_form }}
                                            {{ formset.non_form_errors }}
                                            <thead class="bg-light text-capitalize">
                                                <th style="text-align: center">Item</th>
                                                <th style="text-align: center" id="column_id">Stock Disponible</th>
                                                <th style="text-align: center">Cantidad</th>
                                                <th style="text-align: center">Motivo</th>
                                                <th style="text-align: center"></th>
                                            </thead>
                                            <tbody>
                                                {% for detalle in formset %}
                                                    {{ detalle.id }}
                                                    <tr class="inline {{ formset.prefix }}">
                                                        <td>
                                                            {{detalle.item}}
                                                            {{ detalle.item.errors }}
                                                        </td>
                                                        <td class="column_2">{{detalle.stock_dispobible}} {{ detalle.stock_dispobible.errors }}</td>
                                                        <td> {{detalle.cantidad}} {{ detalle.cantidad.errors }}</td>
                                                        <td> {{detalle.observacion}} {{ detalle.observacion.errors }}</td>
                                                        <td>{{detalle.DELETE}}</td>
                                                    </tr>
                                                {% endfor %}
                                        </table>    

                                    </div>
                                </div>
                                <br>
                            <br>
                            <div class="col-md-12">
                                <div class="col" style="float: left;">
                                    <a class="btn btn-custon-rounded-four btn-primary" onclick="save();" >Guardar</a>

                                    <a class="btn btn-custon-rounded-four btn-default" href="{% url 'AdaptacionStock' %}">Volver</a>
                                </div> 
                                
                            </div>     
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock page_content %}
{% block js %}

<script type="text/javascript">

    $(function () {

        $(".inline.{{ formset.prefix }}").formset({
            prefix: "{{ formset.prefix }}",
            addText: 'Agregar',
            deleteText: 'Remover',

        });

        $("#detalle_tabla").find('.add-row').click(function () {
            add_items();
        })


    });
</script>


{% endblock js %}

taller/stock/templates/AS/AS_delete.html
{% extends 'base/index.html' %}


{% block page_content %}

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">


    <div class="main-content-inner">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">

                        <h4 class="header-title">Eliminar Adaptacion de Stock</h4>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <form method="POST" enctype="multipart/form-data" class="form">
                                {% csrf_token %}
                                    <label for="validationCustom01">Proceso N°:</label>
                                    <!-- <input type="text" class="form-control" id="validationCustom01" placeholder="First name" value="Mark" required=""> -->
                                    <div class="input-group">
                                        {{ object.id}} 
                                    </div>
                                <div class="col" style="float: right;">
                                    <button type="submit" class="btn btn-custon-rounded-four btn-info">Eliminar</button>
                                    <a class="btn btn-custon-rounded-four btn-primary" href="{% url 'AdaptacionStock' %}">Volver</a>
                                </div>
                              </form>  
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock page_content %}
{% block js %}



{% endblock js %}

taller/stock/templates/AS/AS_detalle.html
{% extends 'base/index.html' %}
{% load static %}

{% block extrahead %}
    <script src="{% static 'datos/jquery.formset.js' %}" type="text/JavaScript"></script>
    <script src="{% static 'js/Inputmask/dist/jquery.inputmask.bundle.js' %}"></script>



{% endblock %}
{% block page_content %}
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">


    <div class="main-content-inner">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">

                        <h4 class="header-title">Detalles de Adaptación de Stock</h4>
                        <form method="POST" enctype="multipart/form-data" class="form" id="formulario">
                            {% csrf_token %}
                            <div class="row">

                                <div class="col-sm-8">
                                    <table class="table"> 
                                        <tr>
                                            <th>Ubicación</th>
                                            <td>
                                                {{ obj.ubicacion}}
                                            </td>
                                            
                                        </tr>
                                        <tr>
                                            <th>Procedimiento</th>
                                            <td>
                                                {{ obj.operacion}}
                                            </td>
                                        </tr>
                                        <tr>
                                            <th>Comentario</th>
                                            <td>
                                                {{ obj.observacion}}
                                            </td>
                                        </tr>
                                    </table>
                                    
                                <br>
                                
                            </div>
                           
                            <div class="col-md-12">
                                <hr>
                                <br>
                                <ul id="myTabedu1" class="tab-review-design">
                                    <li class="active"><a href="#description">Detalles</a></li>
                                </ul>
                                <div id="myTabContent" class="tab-content custom-product-edit">
                                    <div class="product-tab-list tab-pane fade active in" id="description">
                                        
                                        <table id="detalle_tabla" class="table table-striped jambo_table scroll">
                                            
                                            <thead class="bg-light text-capitalize">
                                                <th>Item</th>
                                                <th>Cantidad</th>
                                                <th >Motivo</th>
                                            </thead>
                                            <tbody>
                                                {% for detalle in detalles %}
                                                    <tr >
                                                        <td>
                                                            {{detalle.item}}
                                                        </td>
                                                        <td> {{detalle.cantidad}} </td>
                                                        <td> {{detalle.observacion}} </td>
                                                    </tr>
                                                {% endfor %}
                                        </table>    

                                    </div>
                                </div>
                                <br>
                            <br>
                            <div class="col-md-12">
                                <div class="col" style="float: left;">
                                    <a class="btn btn-custon-rounded-four btn-default" href="{% url 'AdaptacionStock' %}">Volver</a>
                                </div> 
                                
                            </div>     
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock page_content %}
{% block js %}




{% endblock js %}